version: '3'
services:
  app:
    build: .
    container_name: funbox-app
    volumes:
      - ./app:/funbox_test/app:ro
      - ./lib:/funbox_test/lib:ro
      - ./log:/funbox_test/log:rw
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    command: bundle exec foreman start

  db:
    image: postgres
    container_name: funbox-postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker

  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    container_name: funbox-redis